### PR TITLE
Updated to work with volkswagen we connect platform

### PR DESCRIPTION
**Pull request by jaybora**
Update to work with new 'we connect' platform.
This is an update for login procedure that has changed quite a lot.
After login, the simple json pages to fetch data from, and to send updates to are unchanged. (apart from the base url)

### CODE REVIEW

**Comment by birgersp** [comment]
Finally got the chance to testing this. Works like a charm!

**Comment by Maverick78de** [comment]
I tried it, I got an error

`Traceback (most recent call last):
  File "bin/carnet_rb.py", line 237, in <module>
    url = CarNetLogin(s,CARNET_USERNAME,CARNET_PASSWORD)
  File "bin/carnet_rb.py", line 100, in CarNetLogin
    login_action_url = auth_base_url + extract_login_action_url(r)
  File "bin/carnet_rb.py", line 48, in extract_login_action_url
    return login_action_url_re.search(r.text).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
`

**Comment by bausi2k** [comment]
I think they changed the login again! when you are logging in on the site, there is now a new screen, and changed urls as far as i recognized

**Comment by Sneak-L8** [comment]
I got further by changing the texts to search for:
login_action_url is just: action="([^"]*)"
relay_state_token is now: <input type="hidden" id="input_relayState" name="relayState" value="([^"]*)"/>
login_csrf is: <input type="hidden" id="csrf" name="_csrf" value="([^"]*)"/>

But now I fail after sending that data => 400 bad request.
I'm working with JavaScript. I changed my old javascript code (ar-net) according to this this changes here. That's why a can't post an updated pathon code.

**Pull request merged**
